# Generated by Django 4.0.4 on 2023-01-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
    ]
