# Generated by Django 4.0.4 on 2023-01-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20230122_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metiers',
        ),
    ]
