# Generated by Django 4.0.4 on 2023-01-22 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0003_delete_metiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metiers_id', models.IntegerField()),
                ('metiers_name', models.CharField(max_length=255)),
                ('metiers_description', models.TextField(max_length=255)),
                ('metiers_image', models.ImageField(default='images/22/11/24/images.png', upload_to='images/%y/%m/%d', verbose_name='images')),
                ('metiers_image2', models.ImageField(default='images2/22/11/24/images2.png', upload_to='images2/%y/%m/%d', verbose_name='images2')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('metiers_detaille', models.TextField(max_length=255)),
            ],
        ),
    ]
