# Generated by Django 4.0.4 on 2023-01-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_initial'),
    ]

    operations = [
    ]
