# Generated by Django 4.0.4 on 2023-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20230123_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metiers',
            name='metiers_detaille',
            field=models.TextField(),
        ),
    ]
