# Generated by Django 4.0.4 on 2023-01-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_metiers_metiers_detaille'),
    ]

    operations = [
        migrations.AddField(
            model_name='metiers',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='metiers',
            name='metiers_description',
            field=models.TextField(),
        ),
    ]
